"""High-level tax report calculator.

Takes a user's transaction list, a tax year, a jurisdiction, and a
cost basis method — returns a TaxReport with:

  - per-disposal rows (for Form 8949-style output)
  - short-term vs long-term subtotals
  - net gain / loss
  - discount applied (AU 50%, DE 100% if LT, etc.)
  - caveats pulled from the jurisdiction config

Everything in this file is pure — no DB, no filesystem — so it's safe to
run inside an API request handler without any async / locking ceremony.
"""
from __future__ import annotations

from dataclasses import dataclass, field, asdict
from datetime import datetime

from .methods import Disposal, compute_disposals, METHODS
from .jurisdictions import Jurisdiction, JURISDICTIONS
from .fx import get_fx_rate
from .self_transfers import filter_self_transfers


@dataclass
class TaxReport:
    """Everything the frontend / PDF renderer needs for a single report.

    Generated by `compute_tax_report`. Serializable to JSON via asdict
    (datetimes become ISO strings in the API layer).
    """
    jurisdiction_code: str
    jurisdiction_name: str
    method: str
    tax_year: int
    currency: str

    # Summary numbers (all in USD — the user converts to local currency
    # themselves using the FX rate for their tax year).
    short_term_proceeds: float
    short_term_cost_basis: float
    short_term_gain: float

    long_term_proceeds: float
    long_term_cost_basis: float
    long_term_gain: float

    total_proceeds: float
    total_cost_basis: float
    total_gain: float

    # Jurisdiction-specific applied adjustments.
    discount_applied_pct: float  # e.g. 0.5 for AU, 0.0 for DE LT
    taxable_gain: float          # after discount, before personal rate

    # Counts for the header.
    disposal_count: int
    asset_count: int

    # FX conversion to the jurisdiction's native currency. All the
    # *_local fields are computed at the year-end rate (see tax.fx) —
    # they're what the user will actually write on their tax form if
    # filing outside the US. fx_is_fresh is False if we had to fall
    # back to a prior year's rate (e.g. 2026 rate not yet published).
    fx_rate_to_local: float = 1.0
    fx_is_fresh: bool = True
    short_term_gain_local: float = 0.0
    long_term_gain_local: float = 0.0
    total_gain_local: float = 0.0
    taxable_gain_local: float = 0.0

    # Detail rows. Kept as plain dicts so dataclass → JSON is painless.
    disposals: list[dict] = field(default_factory=list)
    caveats: list[str] = field(default_factory=list)

    # Generated-at timestamp for the PDF footer.
    generated_at: str = ""


def _filter_to_year(disposals: list[Disposal], year: int,
                    tax_year_end: tuple[int, int]) -> list[Disposal]:
    """Keep only disposals that fall in the given tax year.

    Some jurisdictions don't use calendar years. We model the tax year as
    ending on `tax_year_end`, so the 2024 UK tax year runs from
    2023-04-06 through 2024-04-05 inclusive.
    """
    month, day = tax_year_end
    if (month, day) == (12, 31):
        # Simple calendar year path — faster and easier to reason about.
        return [d for d in disposals if d.disposed_ts.year == year]
    # Fiscal year: ends `year/month/day`, starts the day after `year-1/month/day`.
    end = datetime(year, month, day, 23, 59, 59)
    start_year = year - 1
    # Start the day AFTER the previous year-end.
    start = datetime(start_year, month, day) if (month, day) != (2, 29) \
        else datetime(start_year, 3, 1)
    # Increment by one day.
    from datetime import timedelta
    start = start + timedelta(days=1)
    start = start.replace(hour=0, minute=0, second=0)
    return [d for d in disposals if start <= d.disposed_ts <= end]


def _classify_long_term(disposals: list[Disposal], juris: Jurisdiction) -> None:
    """Mutate disposals in place to set the long_term flag per jurisdiction."""
    threshold = juris.long_term_days
    if threshold is None:
        # No long/short distinction — leave everything short by convention.
        for d in disposals:
            d.long_term = False
        return
    for d in disposals:
        d.long_term = d.holding_days >= threshold


def compute_tax_report(
    transactions: list[dict],
    tax_year: int,
    jurisdiction_code: str = "US",
    method: str = "FIFO",
    spec_id_map: dict[int, dict[int, float]] | None = None,
) -> TaxReport:
    """End-to-end: txs → filtered, classified, discounted report."""
    juris = JURISDICTIONS.get(jurisdiction_code.upper())
    if not juris:
        raise ValueError(f"unknown jurisdiction: {jurisdiction_code}")

    method = method.upper()
    if method not in juris.allowed_methods:
        raise ValueError(
            f"method {method} is not allowed in {juris.name} — "
            f"allowed: {', '.join(juris.allowed_methods)}"
        )

    # Strip self-transfers (withdraw + deposit pairs of the same asset
    # within a short time window) BEFORE the walker runs. These are
    # wallet-to-wallet moves, not real disposals, and treating them as
    # such would both invent phantom gains/losses at the transfer price
    # AND reset the basis of the moved units.
    transactions, self_transfer_ids = filter_self_transfers(transactions)

    # Walk ALL transactions — we need the full history to build lots
    # correctly (a 2020 buy that matches a 2024 sale needs its 2020
    # acquisition date, even though we're only reporting 2024).
    #
    # UK is special: HMRC requires the same-day + 30-day + s104 pool
    # matching rules, which don't fit the simple AVG walker. We route
    # UK reports through the dedicated share-matching module.
    if juris.code == "GB":
        from .uk_matching import compute_disposals_uk
        all_disposals, _lots = compute_disposals_uk(transactions)
    else:
        all_disposals, _lots = compute_disposals(
            transactions, method=method, spec_id_map=spec_id_map,
        )

    # Classify long/short first, THEN filter to tax year. Classification
    # depends on holding period so it's jurisdiction-specific but
    # tax-year-independent.
    _classify_long_term(all_disposals, juris)
    year_disposals = _filter_to_year(
        all_disposals, tax_year, juris.tax_year_end,
    )

    # Aggregate.
    st_proceeds = st_basis = st_gain = 0.0
    lt_proceeds = lt_basis = lt_gain = 0.0
    assets: set[str] = set()

    for d in year_disposals:
        assets.add(d.symbol)
        if d.long_term:
            lt_proceeds += d.proceeds
            lt_basis += d.cost_basis
            lt_gain += d.gain
        else:
            st_proceeds += d.proceeds
            st_basis += d.cost_basis
            st_gain += d.gain

    # Apply jurisdiction discount to long-term gains. Losses are NEVER
    # discounted (you get the full loss back) — that's standard in both
    # AU 50% CGT and DE's exempt hold.
    discount_pct = juris.long_term_discount_pct
    if lt_gain > 0:
        discounted_lt = lt_gain * discount_pct
    else:
        discounted_lt = lt_gain  # losses pass through undiscounted

    taxable = st_gain + discounted_lt
    if not juris.loss_offset_allowed and taxable < 0:
        # India: losses don't offset anything — taxable floor is 0 (but
        # ONLY gains are taxable). We clamp negative totals to 0 and the
        # per-disposal rows still show the losses for the user's records.
        taxable = max(0, st_gain if st_gain > 0 else 0) + \
                  max(0, discounted_lt if discounted_lt > 0 else 0)

    # Serialize disposals to dicts now so the API / PDF layer doesn't
    # have to know about the dataclass. We convert datetimes to ISO
    # strings so json.dumps is happy.
    disposal_dicts: list[dict] = []
    for d in year_disposals:
        disposal_dicts.append({
            "symbol": d.symbol,
            "acquired_ts": d.acquired_ts.isoformat(),
            "disposed_ts": d.disposed_ts.isoformat(),
            "amount": d.amount,
            "cost_basis": d.cost_basis,
            "proceeds": d.proceeds,
            "gain": d.gain,
            "holding_days": d.holding_days,
            "long_term": d.long_term,
            "source_tx_id": d.source_tx_id,
            "lot_id": d.lot_id,
        })
    # Sort by date for the final listing, then by symbol for stable ties.
    disposal_dicts.sort(key=lambda r: (r["disposed_ts"], r["symbol"]))

    # FX conversion — skip for USD jurisdictions (rate is always 1.0
    # anyway, no point in flagging caveats). For everyone else, look up
    # the year-end rate and carry the local-currency figures in the
    # report so the PDF can render them side-by-side with USD.
    fx_rate, fx_fresh = get_fx_rate(tax_year, juris.currency)
    caveats = list(juris.caveats)
    # Transparency caveat: tell the user how many self-transfers were
    # auto-excluded so they can sanity-check (and spot over-matching if
    # the heuristic gets too aggressive on some edge case).
    if self_transfer_ids:
        pair_count = len(self_transfer_ids) // 2
        caveats.append(
            f"Auto-excluded {pair_count} wallet-to-wallet self-transfer "
            f"{'pair' if pair_count == 1 else 'pairs'} "
            f"({len(self_transfer_ids)} transactions) from disposals. "
            f"These are moves between your own wallets, not sales. "
            f"The matcher pairs withdraw+deposit of the same asset "
            f"within 1 hour and 0.5% amount tolerance."
        )
    if juris.currency != "USD":
        if fx_fresh:
            caveats.append(
                f"FX conversion: 1 USD = {fx_rate:g} {juris.currency} "
                f"(year-end {tax_year} rate). Your accountant may prefer "
                f"a different method — some authorities publish an official "
                f"yearly average rate."
            )
        else:
            caveats.append(
                f"FX rate for {tax_year} not yet in our table — using "
                f"the most recent rate we have for {juris.currency} "
                f"(1 USD = {fx_rate:g}). Update before filing if a more "
                f"recent official rate exists."
            )

    return TaxReport(
        jurisdiction_code=juris.code,
        jurisdiction_name=juris.name,
        method=method,
        tax_year=tax_year,
        currency=juris.currency,
        short_term_proceeds=st_proceeds,
        short_term_cost_basis=st_basis,
        short_term_gain=st_gain,
        long_term_proceeds=lt_proceeds,
        long_term_cost_basis=lt_basis,
        long_term_gain=lt_gain,
        total_proceeds=st_proceeds + lt_proceeds,
        total_cost_basis=st_basis + lt_basis,
        total_gain=st_gain + lt_gain,
        discount_applied_pct=discount_pct,
        taxable_gain=taxable,
        fx_rate_to_local=fx_rate,
        fx_is_fresh=fx_fresh,
        short_term_gain_local=st_gain * fx_rate,
        long_term_gain_local=lt_gain * fx_rate,
        total_gain_local=(st_gain + lt_gain) * fx_rate,
        taxable_gain_local=taxable * fx_rate,
        disposal_count=len(year_disposals),
        asset_count=len(assets),
        disposals=disposal_dicts,
        caveats=caveats,
        generated_at=datetime.utcnow().isoformat(timespec="seconds") + "Z",
    )


def compare_methods(
    transactions: list[dict],
    tax_year: int,
    jurisdiction_code: str = "US",
) -> list[dict]:
    """Run every jurisdiction-allowed method and return side-by-side summary.

    This is the killer feature of the report: "if you'd used HIFO instead
    of FIFO this year, you'd owe $X less in taxes". We return a list of
    small dicts rather than full TaxReports to keep the payload small —
    the UI calls `compute_tax_report` again for the method the user
    eventually picks.
    """
    juris = JURISDICTIONS.get(jurisdiction_code.upper())
    if not juris:
        raise ValueError(f"unknown jurisdiction: {jurisdiction_code}")

    results = []
    for method in juris.allowed_methods:
        if method == "SPEC":
            # Spec-ID needs per-tx lot picks — can't meaningfully compare
            # without the user's explicit choices, so we skip it in the
            # auto-comparison view.
            continue
        try:
            report = compute_tax_report(
                transactions, tax_year, juris.code, method,
            )
        except Exception as e:  # noqa: BLE001
            results.append({"method": method, "error": str(e)})
            continue
        results.append({
            "method": method,
            "short_term_gain": report.short_term_gain,
            "long_term_gain": report.long_term_gain,
            "total_gain": report.total_gain,
            "taxable_gain": report.taxable_gain,
            "disposal_count": report.disposal_count,
        })
    # Sort cheapest-taxable-first so the UI can highlight the winner.
    results.sort(key=lambda r: r.get("taxable_gain", 0))
    return results
