"""Tax report renderers: PDF, generic CSV, and Form 8949 CSV.

All three take the same TaxReport object produced by calculator.py and
emit bytes ready to be streamed back by the API layer.

PDF design notes
----------------
The PDF matches the house style from /root/telegram-claude/md_to_pdf.py
— teal accents (#00a7d4), dark code blocks, page numbers — but the
content is hand-rolled HTML so we get tight control over the tables
(Form 8949 format is picky about column order and widths).

Layout per page:
  • Cover block: jurisdiction, year, method, generated timestamp
  • Summary table: short vs long term, net gain, taxable
  • Caveats list (jurisdiction legal boilerplate)
  • Detail table: one row per disposal, sorted by disposal date

For a typical user with a few dozen disposals this comes out to 2-4
pages. Heavy traders may get 20+ pages — we don't paginate aggressively.

CSV formats
-----------
  tax_report.csv    — generic, works with every accountant tool
  form_8949.csv     — IRS Form 8949 Part I / II column layout
                      (Description, Date Acquired, Date Sold, Proceeds,
                       Cost, Adjustment Code, Adjustment Amount, Gain)
"""
from __future__ import annotations

import csv
import io
from datetime import datetime

import markdown  # already a dep (md_to_pdf.py uses it)
import weasyprint

from .calculator import TaxReport


# ---------------------------------------------------------------------------
# Shared CSS — matches md_to_pdf.py house style
# ---------------------------------------------------------------------------
_CSS = """
@page {
    size: A4;
    margin: 1.8cm 1.6cm;
    @bottom-right {
        content: "Page " counter(page) " / " counter(pages);
        font-family: -apple-system, system-ui, sans-serif;
        font-size: 9pt;
        color: #888;
    }
    @bottom-left {
        content: "Generated by crypto-tracker  •  NOT legal advice";
        font-family: -apple-system, system-ui, sans-serif;
        font-size: 8pt;
        color: #aaa;
    }
}
html { font-size: 9.5pt; }
body {
    font-family: -apple-system, "SF Pro Text", "Segoe UI", Helvetica, Arial, sans-serif;
    line-height: 1.45;
    color: #1c1f24;
}
h1 {
    font-size: 22pt;
    color: #0b4c6b;
    border-bottom: 2px solid #00a7d4;
    padding-bottom: 6px;
    margin-top: 0;
    margin-bottom: 4pt;
}
.subtitle {
    color: #5c6872;
    font-size: 11pt;
    margin-bottom: 18pt;
}
h2 {
    font-size: 13pt;
    color: #0b4c6b;
    margin-top: 18pt;
    margin-bottom: 6pt;
    border-bottom: 1px solid #d0d7de;
    padding-bottom: 2pt;
}
.summary-grid {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 10pt 20pt;
    margin: 8pt 0 14pt;
}
.stat {
    background: #f4f6f8;
    border-left: 3px solid #00a7d4;
    padding: 8pt 12pt;
    border-radius: 3px;
}
.stat .label {
    font-size: 8pt;
    color: #5c6872;
    text-transform: uppercase;
    letter-spacing: 0.4px;
}
.stat .value {
    font-size: 14pt;
    color: #0b4c6b;
    font-weight: 600;
    margin-top: 2pt;
}
.stat.neg .value { color: #b54700; }
.stat.highlight {
    background: #e8f5fb;
    border-left-color: #0b4c6b;
}
.stat .sub {
    font-size: 9pt;
    color: #5c6872;
    font-weight: 400;
    margin-top: 2pt;
}
table {
    border-collapse: collapse;
    width: 100%;
    margin: 6pt 0 10pt;
    font-size: 8.5pt;
}
th, td {
    border: 1px solid #d0d7de;
    padding: 4pt 6pt;
    text-align: left;
    vertical-align: top;
}
th {
    background: #f4f6f8;
    color: #0b4c6b;
    font-weight: 600;
    font-size: 8pt;
}
td.num { text-align: right; font-family: "SF Mono", Menlo, Consolas, monospace; }
td.neg { color: #b54700; }
td.pos { color: #0f8a4f; }
.tag {
    display: inline-block;
    padding: 1px 6px;
    border-radius: 8px;
    font-size: 7.5pt;
    font-weight: 600;
    letter-spacing: 0.2px;
}
.tag-lt { background: #e8f5fb; color: #0b4c6b; }
.tag-st { background: #fff3e8; color: #b54700; }
.caveat {
    background: #fff9eb;
    border-left: 3px solid #e6b800;
    padding: 6pt 10pt;
    margin: 4pt 0;
    font-size: 8.5pt;
    color: #5c4a00;
    border-radius: 2px;
}
.footer-note {
    margin-top: 20pt;
    padding-top: 8pt;
    border-top: 1px solid #d0d7de;
    font-size: 8pt;
    color: #888;
}
table, .summary-grid { page-break-inside: avoid; }
h2 { page-break-after: avoid; }
"""


def _fmt_money(v: float, symbol: str = "$") -> str:
    """Format a currency amount with commas and two decimals.

    Negative values wrapped in parens so the CSS can colour them red-ish.
    We keep "($1,234.56)" rather than "-$1,234.56" because that's the
    convention accountants expect. `symbol` defaults to USD but callers
    pass the local-currency symbol for jurisdiction-specific rendering.
    """
    if v < 0:
        return f"({symbol}{abs(v):,.2f})"
    return f"{symbol}{v:,.2f}"


# Map ISO currency codes → display symbol for the PDF header. Anything
# not in this table falls back to the ISO code itself ("£" is prettier
# than "GBP", but "KRW" looks fine without a symbol).
_CURRENCY_SYMBOLS = {
    "USD": "$", "GBP": "£", "EUR": "€", "JPY": "¥", "INR": "₹",
    "CAD": "C$", "AUD": "A$", "SGD": "S$",
}


def _currency_symbol(code: str) -> str:
    return _CURRENCY_SYMBOLS.get((code or "").upper(), f"{code} ")


def _fmt_amount(v: float) -> str:
    """Format a crypto amount — more precision than USD."""
    if v == 0:
        return "0"
    if abs(v) >= 1:
        return f"{v:,.6f}".rstrip("0").rstrip(".")
    return f"{v:.8f}".rstrip("0").rstrip(".")


def _fmt_date(iso_ts: str) -> str:
    """ISO timestamp → "2024-03-15" for table cells."""
    return iso_ts.split("T")[0]


def render_pdf(report: TaxReport) -> bytes:
    """Produce the final PDF as bytes, ready to stream to the user."""
    net = report.total_gain
    net_class = "neg" if net < 0 else ""

    # Summary stat cards.
    st_class = "neg" if report.short_term_gain < 0 else ""
    lt_class = "neg" if report.long_term_gain < 0 else ""

    # Local-currency rendering — only show a second value line when
    # the jurisdiction isn't already USD (otherwise it's just "$X / $X"
    # which looks silly).
    show_local = report.currency and report.currency.upper() != "USD"
    local_sym = _currency_symbol(report.currency)

    def _stat(label: str, usd: float, local: float, css_class: str = "") -> str:
        # If the jurisdiction is non-USD, show the local amount as the
        # headline and the USD as a sub-value. Keeps the PDF native-first
        # for the country being filed in.
        if show_local:
            headline = _fmt_money(local, local_sym)
            sub = f'<div class="sub">{_fmt_money(usd, "$")}</div>'
        else:
            headline = _fmt_money(usd, "$")
            sub = ""
        return (
            f'<div class="stat {css_class}">'
            f'<div class="label">{label}</div>'
            f'<div class="value">{headline}</div>'
            f'{sub}'
            f'</div>'
        )

    summary_html = f"""
    <div class="summary-grid">
      {_stat("Short-Term Gain", report.short_term_gain,
             report.short_term_gain_local, st_class)}
      {_stat("Long-Term Gain", report.long_term_gain,
             report.long_term_gain_local, lt_class)}
      {_stat("Net Gain / Loss", net, report.total_gain_local, net_class)}
      {_stat("Taxable Gain (after discount)", report.taxable_gain,
             report.taxable_gain_local, "highlight")}
    </div>
    """

    # Totals table (matches Form 8949 Part I / Part II shape).
    totals_html = f"""
    <table>
      <thead>
        <tr>
          <th>Term</th>
          <th class="num">Proceeds</th>
          <th class="num">Cost Basis</th>
          <th class="num">Gain / Loss</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>Short-term (&lt; 1 year)</td>
          <td class="num">{_fmt_money(report.short_term_proceeds)}</td>
          <td class="num">{_fmt_money(report.short_term_cost_basis)}</td>
          <td class="num {'neg' if report.short_term_gain < 0 else 'pos'}">
            {_fmt_money(report.short_term_gain)}
          </td>
        </tr>
        <tr>
          <td>Long-term (&ge; 1 year)</td>
          <td class="num">{_fmt_money(report.long_term_proceeds)}</td>
          <td class="num">{_fmt_money(report.long_term_cost_basis)}</td>
          <td class="num {'neg' if report.long_term_gain < 0 else 'pos'}">
            {_fmt_money(report.long_term_gain)}
          </td>
        </tr>
        <tr style="font-weight:600; background:#f4f6f8;">
          <td>Total</td>
          <td class="num">{_fmt_money(report.total_proceeds)}</td>
          <td class="num">{_fmt_money(report.total_cost_basis)}</td>
          <td class="num {'neg' if report.total_gain < 0 else 'pos'}">
            {_fmt_money(report.total_gain)}
          </td>
        </tr>
      </tbody>
    </table>
    """

    # Caveats panel — jurisdiction-specific warnings.
    caveats_html = ""
    if report.caveats:
        items = "".join(f'<div class="caveat">{c}</div>' for c in report.caveats)
        caveats_html = f"<h2>Jurisdiction Notes — {report.jurisdiction_name}</h2>{items}"

    # Disposals detail table.
    disposal_rows = []
    for d in report.disposals:
        tag = ('<span class="tag tag-lt">LT</span>' if d["long_term"]
               else '<span class="tag tag-st">ST</span>')
        gain_class = "neg" if d["gain"] < 0 else "pos"
        disposal_rows.append(f"""
          <tr>
            <td>{d["symbol"]}</td>
            <td class="num">{_fmt_amount(d["amount"])}</td>
            <td>{_fmt_date(d["acquired_ts"])}</td>
            <td>{_fmt_date(d["disposed_ts"])}</td>
            <td class="num">{d["holding_days"]}d</td>
            <td>{tag}</td>
            <td class="num">{_fmt_money(d["cost_basis"])}</td>
            <td class="num">{_fmt_money(d["proceeds"])}</td>
            <td class="num {gain_class}">{_fmt_money(d["gain"])}</td>
          </tr>
        """)

    disposals_html = ""
    if disposal_rows:
        disposals_html = f"""
        <h2>Disposal Detail ({report.disposal_count} rows, {report.asset_count} assets)</h2>
        <table>
          <thead>
            <tr>
              <th>Asset</th>
              <th class="num">Amount</th>
              <th>Acquired</th>
              <th>Disposed</th>
              <th class="num">Held</th>
              <th>Type</th>
              <th class="num">Cost Basis</th>
              <th class="num">Proceeds</th>
              <th class="num">Gain</th>
            </tr>
          </thead>
          <tbody>
            {''.join(disposal_rows)}
          </tbody>
        </table>
        """
    else:
        disposals_html = '<h2>Disposal Detail</h2><p><em>No disposals in this tax year.</em></p>'

    discount_label = ""
    if report.discount_applied_pct != 1.0:
        discount_label = (
            f" &middot; Long-term discount applied: "
            f"{int((1 - report.discount_applied_pct) * 100)}% exempt"
        )

    gen_ts = report.generated_at.replace("T", " ").rstrip("Z")

    html = f"""<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>Tax Report — {report.jurisdiction_name} {report.tax_year}</title>
  <style>{_CSS}</style>
</head>
<body>
  <h1>Crypto Tax Report</h1>
  <div class="subtitle">
    {report.jurisdiction_name} &middot; Tax Year {report.tax_year} &middot;
    Method: <strong>{report.method}</strong>{discount_label}
  </div>

  <h2>Summary</h2>
  {summary_html}
  {totals_html}

  {caveats_html}

  {disposals_html}

  <div class="footer-note">
    Generated {gen_ts} UTC. This report is for your records and does not
    constitute tax or legal advice. Verify totals against your own records
    before filing.
  </div>
</body>
</html>"""

    return weasyprint.HTML(string=html).write_pdf()


def render_csv(report: TaxReport) -> bytes:
    """Generic CSV with every column a tax tool might want."""
    buf = io.StringIO()
    w = csv.writer(buf)
    w.writerow([
        "symbol", "amount", "acquired", "disposed", "holding_days",
        "term", "cost_basis_usd", "proceeds_usd", "gain_usd",
        "source_tx_id", "lot_id",
    ])
    for d in report.disposals:
        w.writerow([
            d["symbol"],
            f"{d['amount']:.10f}".rstrip("0").rstrip("."),
            _fmt_date(d["acquired_ts"]),
            _fmt_date(d["disposed_ts"]),
            d["holding_days"],
            "long" if d["long_term"] else "short",
            f"{d['cost_basis']:.2f}",
            f"{d['proceeds']:.2f}",
            f"{d['gain']:.2f}",
            d.get("source_tx_id") or "",
            d.get("lot_id") or "",
        ])
    return buf.getvalue().encode("utf-8")


def render_form_8949_csv(report: TaxReport) -> bytes:
    """IRS Form 8949 CSV — columns match Part I / Part II line layout.

    Importable by TurboTax (via "CSV upload"), CoinTracker, Koinly, and
    most other tax tools. The first row is a comment identifying the
    term (ST = Part I Box C, LT = Part II Box F) so the consuming tool
    can route rows into the right box.
    """
    buf = io.StringIO()
    w = csv.writer(buf)
    # Header comment row — most tools strip lines starting with "#"
    w.writerow([
        "# Form 8949 export — crypto-tracker",
        f"Jurisdiction: {report.jurisdiction_code}",
        f"Tax year: {report.tax_year}",
        f"Method: {report.method}",
    ])
    w.writerow([
        "Description",  # e.g. "1.5 BTC"
        "Date Acquired",
        "Date Sold",
        "Proceeds",
        "Cost Basis",
        "Adjustment Code",
        "Adjustment Amount",
        "Gain/Loss",
        "Term",  # ST or LT
    ])
    for d in report.disposals:
        description = f"{_fmt_amount(d['amount'])} {d['symbol']}"
        w.writerow([
            description,
            _fmt_date(d["acquired_ts"]),
            _fmt_date(d["disposed_ts"]),
            f"{d['proceeds']:.2f}",
            f"{d['cost_basis']:.2f}",
            "",  # adjustment code (empty = no adjustment)
            "",  # adjustment amount
            f"{d['gain']:.2f}",
            "LT" if d["long_term"] else "ST",
        ])
    return buf.getvalue().encode("utf-8")
